#!/usr/bin/env python3

import h5py
import numpy as np
import tifffile


base = np.ones((15, 128, 128), dtype=np.uint16) * np.arange(15, dtype=np.uint16)[:, np.newaxis, np.newaxis]
fmt = 'multipage-image-{:>02}.{}'


for i in range(4):
    current = base + i * len(base)
    tifffile.imsave(fmt.format(i, 'tif'), current)
    with h5py.File(fmt.format(i, 'h5'), 'w') as f:
        dset = f.create_dataset('images', data=current)
    with open(fmt.format(i, 'raw'), 'wb') as f:
        f.write(current.tostring())
